# Site settings
title: My Data Science Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my data science portfolio. Here you'll find my projects, blog posts, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Author settings
author:
  name: Your Name
  email: your-email@example.com

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Social media settings
twitter_username: your_twitter_username
github_username: your_github_username
linkedin_username: your_linkedin_username

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Include additional files
include:
  - _pages

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Custom variables
custom_variable: "This is a custom variable"

# Navigation links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"

# Disqus comments
disqus_shortname: "your_disqus_shortname"
